# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pancake.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("pancake.proto", :syntax => :proto3) do
    add_message "pancake.Pancake" do
      optional :chef_name, :string, 1
      optional :menu, :enum, 2, "pancake.Pancake.Menu"
      optional :technical_score, :float, 3
      optional :create_time, :message, 15, "google.protobuf.Timestamp"
    end
    add_enum "pancake.Pancake.Menu" do
      value :UNKNOWN, 0
      value :CLASSIC, 1
      value :BANANA_AND_WHIP, 2
      value :BACON_AND_CHEESE, 3
      value :MIX_BERRY, 4
      value :BAKED_MARSHMALLOW, 5
      value :SPICY_CURRY, 6
    end
    add_message "pancake.Report" do
      repeated :bake_counts, :message, 1, "pancake.Report.BakeCount"
    end
    add_message "pancake.Report.BakeCount" do
      optional :menu, :enum, 1, "pancake.Pancake.Menu"
      optional :count, :int32, 2
    end
    add_message "pancake.BakeRequest" do
      optional :menu, :enum, 1, "pancake.Pancake.Menu"
    end
    add_message "pancake.BakeResponse" do
      optional :pancake, :message, 1, "pancake.Pancake"
    end
    add_message "pancake.ReportRequest" do
    end
    add_message "pancake.ReportResponse" do
      optional :report, :message, 1, "pancake.Report"
    end
  end
end

module Pancake
  Pancake = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pancake.Pancake").msgclass
  Pancake::Menu = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pancake.Pancake.Menu").enummodule
  Report = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pancake.Report").msgclass
  Report::BakeCount = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pancake.Report.BakeCount").msgclass
  BakeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pancake.BakeRequest").msgclass
  BakeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pancake.BakeResponse").msgclass
  ReportRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pancake.ReportRequest").msgclass
  ReportResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pancake.ReportResponse").msgclass
end
